config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'

  resources :tv_shows do
    collection do
      post :get_tv_shows
      post :get_tv_show_info
      post :get_tv_season_info
      post :get_tv_episode_info
    end
  end

  resources :tv_seasons
  resources :tv_episodes

  resources :games do
    collection do
      post :get_barcode
      post :get_game_info
      post :get_games
    end
  end

  devise_for :users

  devise_scope :user do
    get "auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    get "auth/google/callback"   => "users/omniauth_callbacks#google"
    get "auth/linkedin/callback" => "users/omniauth_callbacks#linkedin"
    get "auth/github/callback"   => "users/omniauth_callbacks#github"
  end

  post '/favorites/:movieId'                =>  'favorites#create'
  delete '/favorites/destroy/:movieId'      =>  'favorites#destroy'

  post '/game_favorites/:gameId'            =>  'game_favorites#create'
  delete '/game_favorites/destroy/:gameId'  =>  'game_favorites#destroy'

  post '/tv_favorites/:tvshowId'                =>  'tv_favorites#create'
  delete '/tv_favorites/destroy/:tvshowId'      =>  'tv_favorites#destroy'

  get 'pages/landing'
  get 'pages/comingsoon'
  root 'pages#landing'

  resources :people

  resources :movies do
    collection do
      post :get_barcode
      post :get_movie_info
      post :get_movies
    end
  end

  mount Resque::Server.new, at: "/resque"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :movie_casts, dependent: :destroy
  has_many :movies_as_cast, through: :movie_casts, class_name: "Movie", source: :movie
  has_many :movie_crews, dependent: :destroy
  has_many :movies_as_crew, through: :movie_crews, class_name: "Movie", source: :movie

  has_many :tv_creators, dependent: :destroy
  has_many :tv_shows, through: :tv_creators

  has_many :tv_casts, dependent: :destroy
  has_many :tv_seasons, through: :tv_casts

  has_many :tv_guest_stars, dependent: :destroy
  has_many :tv_episodes, through: :tv_guest_stars

  validates :name, presence: true
  validates :tmdb_people_id, presence: true

  def self.get_person_details(tmdb_people_id)
    response = HTTParty.get("https://api.themoviedb.org/3/person/#{tmdb_people_id}", query:
    {
      api_key: ENV['TMDB_API_KEY'],
      language: "en-US"
      })
    person_details = JSON.parse(response.body)

    name = person_details["name"]
    tmdb_people_id = person_details["id"]
    biography = person_details["biography"]
    birthday = person_details["birthday"]
    deathday = person_details["deathday"]
    place_of_birth = person_details["place_of_birth"]
    gender = person_details["gender"]
    if person_details["profile_path"].nil?
      profile_path_url = person_details["profile_path"]
    else
      profile_path_url = "http://image.tmdb.org/t/p/w185/#{person_details["profile_path"]}"
    end

    person_params = {name: name, tmdb_people_id: tmdb_people_id, biography: biography, birthday: birthday, deathday: deathday, place_of_birth: place_of_birth, gender: gender, profile_path_url: profile_path_url}

    return person_params
  end

  def self.process_cast(credits, movieid)
    @cast_members = credits["cast"]
    @cast_members.each do |cast|
      character = cast["character"]
      order = cast["order"]
      tmdb_people_id = cast["id"]
      @person = Person.find_by(tmdb_people_id: tmdb_people_id)
      if @person.nil?
        person_params = Person.get_person_details(tmdb_people_id)
        @person = Person.create(person_params)
        Resque.enqueue(Sleeper, 1)
        cast_params = {movie_id: movieid, person_id: @person.id, character: character, order: order}
        @cast_member = MovieCast.create(cast_params)
      else
        cast_params = {movie_id: movieid, person_id: @person.id, character: character, order: order}
        @cast_member = MovieCast.create(cast_params)
      end
    end
  end

  def self.process_crew(credits, movieid)
    @crew_members = credits["crew"]
    @crew_members.each do |crew|
      department = crew["department"]
      job = crew["job"]
      next unless department == "Directing" || department == "Writing"
      tmdb_people_id = crew["id"]
      @person = Person.find_or_initialize_by(tmdb_people_id: tmdb_people_id)
      if @person.new_record?
        person_params = Person.get_person_details(tmdb_people_id)
        @person = Person.create(person_params)
        crew_params = {movie_id: movieid, person_id: @person.id, department: department, job: job}
        @crew_member = MovieCrew.create(crew_params)
      else
        crew_params = {movie_id: movieid, person_id: @person.id, department: department, job: job}
        @crew_member = MovieCrew.create(crew_params)
      end
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!

  # GET /people
  def index
    if params[:search]
      @people = Person.search(params[:search]).page(params[:page]).per(50).order('name')
    elsif params[:sort] == 'name'
      @people = Person.page(params[:page]).per(50).order('name')
    elsif params[:sort] == 'created_at'
      @people = Person.page(params[:page]).per(50).order('created_at DESC')
    else
      @people = Person.page(params[:page]).per(50).order('name')
    end
  end

  def create
    @person = Person.new
    @person.name = params[:name]
    @person.tmdb_people_id = params[:tmdb_people_id]
    @person.gender = params[:gender]
    @person.biography = params[:biography]
    @person.birthday = params[:birthday]
    @person.deathday = params[:deathday]
    @person.place_of_birth = params[:place_of_birth]
    @person.profile_path_url = params[:profile_path_url]
    @person.save!
  end

  def show
    @person = Person.find(params[:id])
    @moviescast = @person.movies_as_cast.all + @person.movies_as_crew.all
    @moviescast.uniq!
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # PATCH/PUT /people/1
  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def person_params
    params.require(:person).permit(:name, :tmdb_people_id, :biography, :birthday, :deathday, :place_of_birth, :profile_path_url, :gender)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @person.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h4>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# name %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <%# birthday %>
  <div class="form-group">
    <%= f.label :birthday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :birthday, class: "form-control" %>
    </div>
  </div>

  <%# place_of_birth %>
  <div class="form-group">
    <%= f.label :place_of_birth, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :place_of_birth, class: "form-control" %>
    </div>
  </div>

  <%# tmdb_people_id %>
  <div class="form-group">
    <%= f.label :tmdb_people_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :tmdb_people_id, class: "form-control" %>
    </div>
  </div>

  <%# deathday %>
  <div class="form-group">
    <%= f.label :deathday, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :deathday, class: "form-control" %>
    </div>
  </div>

  <%# biography %>
  <div class="form-group">
    <%= f.label :biography, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :biography, class: "form-control" %>
    </div>
  </div>

  <%# profile_path_url %>
  <div class="form-group">
    <%= f.label :profile_path_url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :profile_path_url, class: "form-control" %>
    </div>
  </div>


  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10" id="form-click">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>

<% end -%>

app/views/people/edit.html.erb
<div class="container">
  <div class="page-header custom-header">
    <%= link_to @person, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-info-sign"></span>
      Show
    <% end %>
    <h1>Editing Person</h1>
  </div>
</div>

<div class="container">
  <%= render 'form' %>
</div>

app/views/people/index.html.erb
<div class="container">
  <div class="page-header custom-header">
    <div class="header-flexbox">
      <div class="flextitle">
        <h1 Listing>Movie People </h1>
      </div>
      <div class="social-flexbox">
        <div class="well well-sm custom-well text-center">
          <h5>Share what you are watching with your friends!</h5>
          <div class="text-center">
            <%= social_share_button_tag %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <ul class="s-ul">
    <%- @people.each do |person| %>
    <li class="box">
      <% if person.profile_path_url.nil? || person.profile_path_url.empty? %>
        <%= link_to person do %>
          <%= image_tag("genericperson.png") %>
        <% end %>
      <% else %>
        <%= link_to person do %>
          <%= image_tag person.profile_path_url %>
        <% end %>
      <% end %>
      <div class="textline">
        <div class="firsttextline">
          <%= link_to person do %>
            <p class="s-text"><%= person.name %></p>
          <% end %>
        </div>
      </div>
      <div class="textline">
        <p class="s-text secondtextline"><%= person.birthday %></p>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<div class="text-center" id='paginator'>
  <!-- <%= paginate @people, remote: true %><br> -->
  <%= paginate @people do %>
    <nav>
      <ul class="pagination pagination-lg">
        <%= first_page_tag unless current_page.first? %>
        <%= prev_page_tag unless current_page.first? %>
        <% each_page do |page| %>
          <% if page.left_outer? || page.right_outer? || page.inside_window? %>
            <%= page_tag page %>
          <% end %>
        <% end %>
        <%= next_page_tag unless current_page.last? %>
        <%= last_page_tag unless current_page.last? %>
      </ul>
    </nav>
  <% end %>
  <%= page_entries_info @people %>
<p>Logged in as <%= current_user.email %></p>
</div>

app/views/people/show.html.erb
<div class="container">
  <div class="page-header custom-header">
    <div class="header-flexbox">
      <div class="flextitle">
        <h1 Listing>About this Person</h1>
      </div>
      <div class="social-flexbox">
        <div class="well well-sm custom-well text-center">
          <h5>Share with your friends!</h5>
          <div class="text-center">
            <%= social_share_button_tag(@person.name, :url => "http://my-media-library.com", allow_sites: %w(twitter facebook linkedin)) %>
          </div>
        </div>
      </div>
      <div>
        <%= link_to movies_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        Back
        <% end %>
        <% if current_user.email == 'smoline@gmail.com' %>
          <%= link_to @person, class:'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          Delete
          <% end %>
          <%= link_to edit_person_path(@person), class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
          <% end %>
          <%= link_to people_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          People
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="media">
    <div class="media-left col-md-3 text-center col-xs-12">
      <% if @person.profile_path_url.nil? || @person.profile_path_url.empty? %>
        <%= image_tag("genericperson.png") %>
      <% else %>
        <%= image_tag @person.profile_path_url %>
      <% end %>
    </div>
    <div class="media-body">
      <h3 class="media-heading custom-media-heading"><%= @person.name %></h3>
      <p class="custom-media"><strong>Birthday: </strong><%= @person.birthday %></p>
      <p class="custom-media"><strong>Birthplace: </strong><%= @person.place_of_birth %></p>
      <% if @person.deathday != "" %>
        <p class="custom-media"><strong>Date of Death: </strong><%= @person.deathday %></p>
      <% end %>
      <p class="custom-media"><%= @person.biography %></p>
    </div>
  </div>
    <h3 class="custom-media-heading">Movies they are associated with that you own:</h3>
  <div class="show-flexbox">
    <% @moviescast.each do |moviecast| %>
      <% if current_user.owned_movies.include?(moviecast) %>
      <p class="inner-show-flexbox"><%= link_to movie_path(moviecast.id) do %>
        <%= image_tag moviecast.movie_image_url %>
      <% end %></p>
      <% end %>
    <% end %>
  </div>
</div>