config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'

  resources :tv_shows do
    collection do
      post :get_tv_shows
      post :get_tv_show_info
      post :get_tv_season_info
      post :get_tv_episode_info
    end
  end

  resources :tv_seasons
  resources :tv_episodes

  resources :games do
    collection do
      post :get_barcode
      post :get_game_info
      post :get_games
    end
  end

  devise_for :users

  devise_scope :user do
    get "auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    get "auth/google/callback"   => "users/omniauth_callbacks#google"
    get "auth/linkedin/callback" => "users/omniauth_callbacks#linkedin"
    get "auth/github/callback"   => "users/omniauth_callbacks#github"
  end

  post '/favorites/:movieId'                =>  'favorites#create'
  delete '/favorites/destroy/:movieId'      =>  'favorites#destroy'

  post '/game_favorites/:gameId'            =>  'game_favorites#create'
  delete '/game_favorites/destroy/:gameId'  =>  'game_favorites#destroy'

  post '/tv_favorites/:tvshowId'                =>  'tv_favorites#create'
  delete '/tv_favorites/destroy/:tvshowId'      =>  'tv_favorites#destroy'

  get 'pages/landing'
  get 'pages/comingsoon'
  root 'pages#landing'

  resources :people

  resources :movies do
    collection do
      post :get_barcode
      post :get_movie_info
      post :get_movies
    end
  end

  mount Resque::Server.new, at: "/resque"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  # GET /movies
  def index
    if params[:search]
      @movies = Movie.search(params[:search], current_user.id).page(params[:page]).per(24).order('title')
    elsif params[:sort] == 'title'
      @movies = current_user.owned_movies.page(params[:page]).per(24).order('title')
    elsif params[:sort] == 'release_date'
      @movies = current_user.owned_movies.page(params[:page]).per(24).order('release_date DESC')
    elsif params[:sort] == 'created_at'
      @movies = current_user.owned_movies.page(params[:page]).per(24).order('owners.created_at DESC')
    elsif params[:sort] == 'favorites'
      @movies = current_user.favorite_movies.page(params[:page]).per(24).order('title')
    else
      @movies = current_user.owned_movies.page(params[:page]).per(24).order('title')
    end
  end

  # GET /movies/1
  def show
    @movie = Movie.find(params[:id])
    @genres = @movie.genres.all
    @actors = @movie.movie_casts.all
    @crews = @movie.movie_crews.all
    @owner_info = @movie.owners.find_by(user_id: current_user.id)
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @movie.title = params[:title]
    @movie.description = params[:description]
    @movie.release_date = params[:release_date]
    @movie.tmdb_id = params[:tmdb_id]
    @movie.runtime = params[:runtime]
    @movie.tagline = params[:tagline]
    @movie.movie_image_url = params[:movie_image_url]
    @owner_info = @movie.owners.new
    @owner_info.upc = params[:upc]
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
    @owner_info = @movie.owners.find_by(user_id: current_user.id)
  end

  # POST /movies
  def create
    @movie = Movie.new(movie_params)
    @movie.owners.first.user_id = current_user.id

    if @movie.save
      movieid = @movie.id
      more_movie_info = Movie.find_more_movie_info(@movie.tmdb_id)
      @movie_genres = more_movie_info["genres"]
      @movie_genres.each do |thisgenre|
        genreid = thisgenre["id"]
        name = thisgenre["name"]
        @genre = Genre.find_or_create_by(tmdb_genre_id: genreid, name: name)
        @movie.genres << @genre
      end
      credits = Movie.get_movie_credits(@movie.tmdb_id)
      Person.process_cast(credits, movieid)
      Person.process_crew(credits, movieid)
      redirect_to @movie, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /movies/1
  def update
    @movie = current_user.owned_movies.find_by(id: params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /movies/1
  def destroy
    @movie = Movie.find(params[:id])
    @owner = @movie.owners.find_by(user_id: current_user.id)
    # @movie.destroy
    @owner.destroy
    redirect_to movies_url, notice: 'Movie was successfully removed from your list.'
  end

  def get_barcode
    upc = params[:upc]
    @owned_movie = Owner.find_or_initialize_by(upc: params[:upc], user_id: current_user.id)
    if @owned_movie.new_record?
      title = Movie.find_movie_title(upc)
      @movie_info = Movie.find_initial_movie_info(title)
      render json: @movie_info
    else
      redirect_to @movie
    end
  end

  def get_movies
    title = params[:title]
    @movie = Movie.find_or_initialize_by(title: params[:title])
    if @movie.new_record?
      @movie_info = Movie.find_initial_movie_info(title)
      render json: @movie_info
    else
      redirect_to @movie
    end
  end

  def get_movie_info
    upc = params[:upc]
    more_movie_info = Movie.find_more_movie_info(params[:tmdb_id])
    @movie = Movie.find_or_initialize_by(tmdb_id: params[:tmdb_id])
    if @movie.new_record?
      if more_movie_info["poster_path"].nil?
        movie_image_url = more_movie_info["poster_path"]
      else
        movie_image_url = "http://image.tmdb.org/t/p/w185/#{more_movie_info["poster_path"]}"
      end
      movie_params = more_movie_info.merge(
                    upc: params[:upc],
                    tmdb_id: params[:tmdb_id],
                    description: more_movie_info["overview"],
                    movie_image_url: movie_image_url)
      redirect_to new_movie_path(movie_params)
    else
      @movie.owners.create(user_id: current_user.id, movie_id: @movie.id, upc: params[:upc], notes: params[:notes])
      redirect_to @movie
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def movie_params
    params.require(:movie).permit(:title, :tmdb_id, :description, :release_date, :runtime, :tagline, :movie_image_url, owners_attributes: [:id, :user_id, :upc, :notes, :image])
    # owners_attributes: Owner.attribute_names.map(&:to_sym)
    # owners_attributes: [:id, :upc, :notes, :image]
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_empty_movies.html.erb
<div class="jumbotron">
  <h1>Nothing Matched</h1>
</div>

app/views/movies/_form.html.erb
<%= form_for(@movie, html: { class: "form-horizontal new-movie-form", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @movie.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h4>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# title %>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <%# description %>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <%# release_date %>
  <div class="form-group">
    <%= f.label :release_date, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :release_date, class: "form-control" %>
    </div>
  </div>

  <%# runtime %>
  <div class="form-group">
    <%= f.label :runtime, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.number_field :runtime, class: "form-control" %>
    </div>
  </div>

  <%# tagline %>
  <div class="form-group">
    <%= f.label :tagline, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :tagline, class: "form-control" %>
    </div>
  </div>

  <%# tmdb_id %>
  <%= f.hidden_field :tmdb_id, class: "form-control" %>

  <%# image_url %>
  <div class="form-group">
    <%= f.label :movie_image_url, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :movie_image_url, class: "form-control" %>
    </div>
  </div>

  <%= f.fields_for :owners, @owner_info do |builder| %>
    <%= render 'ownerform', f: builder %>
  <% end %>

  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9" id="form-click">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>

<% end -%>

app/views/movies/_movie.html.erb
  <li class="box">
    <% if movie.owners.find_by(user_id: current_user.id).image.attached? %>
      <%= link_to movie do %>
        <%= image_tag movie.owners.find_by(user_id: current_user.id).image, width: '185px' %>
      <% end %>
    <% elsif movie.movie_image_url.nil? || movie.movie_image_url.empty? %>
      <%= link_to movie do %>
        <%= image_tag("genericperson.png") %>
      <% end %>
    <% else %>
      <%= link_to movie do %>
        <%= image_tag movie.movie_image_url %>
      <% end %>
    <% end %>
    <div class="textline">
      <div class="firsttextline">
        <%= link_to movie do %>
          <p class="s-text"><%= truncate(movie.title, length: 44, seperator: ' ') %></p>
        <% end %>
      </div>
    </div>
    <div class="textline">
      <p class="s-text secondtextline yearage" data-showing-age="false" data-age="<%= movie.year_age %>" data-release="<%= movie.release_date %>"><%= movie.release_date %></p>
      <p class="s-text secondtextline minhour" data-showing-hours="false" data-hours="<%= movie.runtime_hours %>" data-mins="<%= movie.runtime %>"><%= movie.runtime %> Mins.</p>
      <div class="heartbox">
        <% if user_signed_in? && favorited(movie.id) == true %>
        <p class="faved-heart" data-remote=true data-type=script data-movieid="<%= movie.id %>"><i class="fa fa-heart" aria-hidden="true"></i></p>
        <% elsif user_signed_in? && favorited(movie.id) == false %>
        <p class="fav-heart" data-remote=true data-type=script data-movieid="<%= movie.id %>"><i class="fa fa-heart" aria-hidden="true"></i></p>
        <% end %>
      </div>
    </div>
  </li>

app/views/movies/_ownerform.html.erb
  <%# upc %>
  <div class="form-group">
    <%= f.label :upc, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.number_field :upc, class: "form-control" %>
    </div>
  </div>

  <%# notes %>
  <div class="form-group">
    <%= f.label :notes, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :notes, class: "form-control" %>
    </div>
  </div>

  <%# image_upload %>
  <div class="form-group">
    <%= f.label :image, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.file_field :image %>
    </div>
  </div>

app/views/movies/edit.html.erb
<div class="container">
  <div class="page-header custom-header">
    <%= link_to movies_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to @movie, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-info-sign"></span>
      Show
    <% end %>
    <h1>Editing movie</h1>
  </div>
</div>

<div class="container">
  <%= render 'form' %>
</div>

app/views/movies/index.html.erb
<div class="container">
  <div class="page-header custom-header">
    <div class="header-flexbox">
      <div class="flextitle">
        <h1 Listing>My Movies </h1>
      </div>
      <div class="social-flexbox">
        <div class="well well-sm custom-well text-center">
          <h5>Share what you are watching with your friends!</h5>
          <div class="text-center">
            <%= social_share_button_tag %>
          </div>
        </div>
      </div>
      <div>
      <%= link_to new_movie_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-plus"></span>
        Add Movie
      <% end %>
    </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="s-ul">
    <%= render @movies %>
  </div>

  <div class="text-center" id='paginator'>
    <%= paginate @movies, remote: true %><br>
    <%= page_entries_info @movies %>
    <p>Logged in as <%= current_user.email %></p>
  </div>
  <div class="col-md-2 col-md-offset-10 text-center api-logo">
      <a href="https://www.themoviedb.org/?language=en" height="50px"><%= image_tag("408x161-powered-by-rectangle-green sm.png") %></a>
  </div>
</div>

app/views/movies/index.js.erb
<% if @movies.empty? %>
  $('.s-ul').html('<%= j(render 'empty_movies') %>')
<% else %>
  $('.s-ul').html('<%= j(render @movies) %>');
  $('.pagination').html('<%= j(paginate(@movies, :remote => true).to_s) %>');
<% end %>

app/views/movies/new.html.erb
<div class="container">
  <div class="page-header custom-header">
    <%= link_to movies_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>

    <a class="btn btn-default" id='btn-scanner'><span class="glyphicon glyphicon-barcode"></span> Search by UPC</a>

    <a class="btn btn-default" id='btn-title-search'><span class="glyphicon glyphicon-th"></span> Search by Title</a>

    <h1>New movie</h1>
  </div>

  <div class="row">
    <div class="col-md-6 col-xs-12">
      <div id='title-search'>
        <div class="search-flexbox">
          <div class="form-inline">
            <div class="form-group">
              <%= text_field_tag :movie_title, params[:movie_title], id: 'movie-title', class: "form-control", placeholder: "Please type the Title of the Movie Here", style: 'width: 400px' %>
            </div>
            <div class="btn btn-default" id='search-title'>
              <span class="glyphicon glyphicon-search"></span> Search
            </div>
          </div>
        </div>
      </div>
      <div class="scanner-flexbox">
        <div class="panel panel-default" id='show-scanner'>
          <div class="panel-heading">
            <h3 class="panel-title barcode-scanner-title">Barcode Scanner</h3>
          </div>
          <div class="panel-body">
            <div id='barcode-scanner'></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-xs-12">
        <%= render 'form' %>
    </div>
    <div class="spinner">
      <div class="sk-circle1 sk-circle"></div>
      <div class="sk-circle2 sk-circle"></div>
      <div class="sk-circle3 sk-circle"></div>
      <div class="sk-circle4 sk-circle"></div>
      <div class="sk-circle5 sk-circle"></div>
      <div class="sk-circle6 sk-circle"></div>
      <div class="sk-circle7 sk-circle"></div>
      <div class="sk-circle8 sk-circle"></div>
      <div class="sk-circle9 sk-circle"></div>
      <div class="sk-circle10 sk-circle"></div>
      <div class="sk-circle11 sk-circle"></div>
      <div class="sk-circle12 sk-circle"></div>
    </div>
  </div>
</div>


<div class="modal fade" id="choose-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Click on the Correct Item</h4>
      </div>
      <div class="modal-body">
        <ul class="custom-choice" id='movies-info'>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="refresh-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body text-center" id='went-wrong-notice'>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="refresh-ok" data-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/movies/show.html.erb
<div class="container">
  <div class="page-header custom-header">
    <div class="header-flexbox">
      <div class="flextitle">
        <h1 Listing>Movie Details </h1>
      </div>
      <div class="social-flexbox">
        <div class="well well-sm custom-well text-center">
          <h5>Share what you are watching with your friends!</h5>
          <div class="text-center">
            <%= social_share_button_tag(@movie.title, :url => "http://my-media-library.com", allow_sites: %w(twitter facebook linkedin)) %>
          </div>
        </div>
      </div>
      <div>
        <%= link_to movies_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-list-alt"></span>
        Back
        <% end %>
        <%= link_to @movie, class:'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        Delete
        <% end %>
        <%= link_to edit_movie_path(@movie), class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-pencil"></span>
        Edit
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container s-media">
  <% if current_user.owned_movies.include?(@movie) %>
  <div class="media">
    <div class="media-left col-md-3 text-center col-xs-12">
        <% if @owner_info.image.attached? %>
          <%= image_tag @owner_info.image, class:'mainimage', width: '185px' %>
        <%elsif @movie.movie_image_url.nil? || @movie.movie_image_url.empty? %>
          <%= image_tag("genericperson.png") %>
        <% else %>
            <%= image_tag @movie.movie_image_url %>
        <% end %>
    </div>
    <div class="media-body">
      <h3 class="media-heading custom-media-heading"><%= @movie.title %></h3>
      <% if user_signed_in? && favorited(@movie.id) == true %>
        <p class="faved-heart" data-remote=true data-type=script data-movieid="<%= @movie.id %>"><i class="fa fa-heart" aria-hidden="true"></i></p>
      <% elsif user_signed_in? && favorited(@movie.id) == false %>
        <p class="fav-heart" data-remote=true data-type=script data-movieid="<%= @movie.id %>"><i class="fa fa-heart" aria-hidden="true"></i></p>
      <% end %>
      <p class="custom-media"><%= @movie.tagline %></p>
      <p class="custom-media yearage" data-showing-age="false" data-age="<%= @movie.year_age %>" data-release="<%= @movie.release_date %>"><strong>Release date: </strong><%= @movie.release_date %></p>
      <p class="custom-media minhour" data-showing-hours="false" data-hours="<%= @movie.runtime_hours %>" data-mins="<%= @movie.runtime %>"><strong>Runtime: </strong><%= @movie.runtime %> Mins.</p>
      <p class="custom-media"><%= @movie.description %></p>
      <p class="custom-media"><strong>Genres: </strong>
        <% @genres.each do |genre| %>
        - <%= genre.name %>
        <% end %>
      </p>
      <p class="custom-media"><strong>Location Notes: </strong><%= @owner_info.notes %></p>
      <p class="custom-media"><strong>UPC: </strong><%= @owner_info.upc %></p>
    </div>
  </div>
  <div class="col-md-6 col-xs-12">
    <h3 class="custom-media-heading">Cast:</h3>
    <% @actors.each do |actor| %>
      <%= link_to person_path(actor.person.id) do %>
        <h5 class="custom-media"><%= actor.name %> - <%= actor.character %></h5>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-6 col-xs-12">
    <h3 class="custom-media-heading">Crew:</h3>
    <% @crews.each do |crew| %>
      <%= link_to person_path(crew.person.id) do %>
        <h5 class="custom-media"><%= crew.name %> - <%= crew.job %></h5>
      <% end %>
    <% end %>
  </div>
  <% end %>
</div>