config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'

  resources :tv_shows do
    collection do
      post :get_tv_shows
      post :get_tv_show_info
      post :get_tv_season_info
      post :get_tv_episode_info
    end
  end

  resources :tv_seasons
  resources :tv_episodes

  resources :games do
    collection do
      post :get_barcode
      post :get_game_info
      post :get_games
    end
  end

  devise_for :users

  devise_scope :user do
    get "auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    get "auth/google/callback"   => "users/omniauth_callbacks#google"
    get "auth/linkedin/callback" => "users/omniauth_callbacks#linkedin"
    get "auth/github/callback"   => "users/omniauth_callbacks#github"
  end

  post '/favorites/:movieId'                =>  'favorites#create'
  delete '/favorites/destroy/:movieId'      =>  'favorites#destroy'

  post '/game_favorites/:gameId'            =>  'game_favorites#create'
  delete '/game_favorites/destroy/:gameId'  =>  'game_favorites#destroy'

  post '/tv_favorites/:tvshowId'                =>  'tv_favorites#create'
  delete '/tv_favorites/destroy/:tvshowId'      =>  'tv_favorites#destroy'

  get 'pages/landing'
  get 'pages/comingsoon'
  root 'pages#landing'

  resources :people

  resources :movies do
    collection do
      post :get_barcode
      post :get_movie_info
      post :get_movies
    end
  end

  mount Resque::Server.new, at: "/resque"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  has_many :tv_favorites, dependent: :destroy

  has_many :tv_genres, dependent: :destroy
  has_many :genres, through: :tv_genres

  has_many :tv_creators, dependent: :destroy
  has_many :people, through: :tv_creators

  has_many :tv_seasons, dependent: :destroy, inverse_of: :tv_show
  accepts_nested_attributes_for :tv_seasons

  def self.find_initial_tv_show_info(name)
    name_new = name

    response = HTTParty.get("https://api.themoviedb.org/3/search/tv", query: {
      api_key: ENV['TMDB_API_KEY'],
      language: "en-US",
      query: name_new,
      page: 1
      })

    tv_show_info = JSON.parse(response.body)["results"]
    return tv_show_info
  end

  def self.find_more_tv_show_info(tmdb_show_id)
    response = HTTParty.get("https://api.themoviedb.org/3/tv/#{tmdb_show_id}", query:
    {
      api_key: ENV['TMDB_API_KEY'],
      language: "en-US"
      })
    more_tv_show_info = JSON.parse(response.body)
    return more_tv_show_info
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :authenticate_user!
  # GET /tv_shows
  def index
    @tv_shows = current_user.tv_shows.all.page(params[:page]).per(24).order('name')
  end

  # GET /tv_shows/1
  def show
    @tv_show = TvShow.find(params[:id])
    @tv_season = @tv_show.tv_seasons.all
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
    @tv_show.tmdb_show_id = params[:tmdb_show_id]
    @tv_show.name = params[:name]
    @tv_show.overview = params[:overview]
    @tv_show.first_air_date = params[:first_air_date]
    @tv_show.last_air_date = params[:last_air_date]
    @tv_show.number_of_seasons = params[:number_of_seasons]
    @tv_show.number_of_episodes = params[:number_of_episodes]
    @tv_show.show_poster_path = params[:show_poster_path]
    @tv_season_info = @tv_show.tv_seasons.new
    @tv_season_info.name = params[:season_name]
    @tv_season_info.tmdb_season_id = params[:tmdb_season_id]
    @tv_season_info.overview = params[:season_overview]
    @tv_season_info.air_date = params[:season_air_date]
    @tv_season_info.season_number = params[:season_number]
    @tv_season_info.season_poster_path = params[:season_poster_path]
    @tv_episode_info = @tv_season_info.tv_episodes.new
    @tv_episode_info.title = params[:episode_title]
    @tv_episode_info.tmdb_episode_id = params[:tmdb_episode_id]
    @tv_episode_info.description = params[:episode_description]
    @tv_episode_info.air_date = params[:episode_air_date]
    @tv_episode_info.episode_number = params[:episode_number]
    @tv_episode_info.season_number = params[:season_number]
    @tv_episode_info.episode_image_url = params[:episode_image_url]
    @tv_owner_info = @tv_episode_info.tv_owners.new
  end

  # GET /tv_shows/1/edit
  def edit
    @tv_show = TvShow.find(params[:id])
    @tv_owner_info = @tv_show.tv_owners.find_by(user_id: current_user.id)
  end

  # POST /tv_shows
  def create
    @tv_show = TvShow.new(tv_show_params)
    @tv_season_info = @tv_show.tv_seasons.new(tv_show_params["tv_seasons_attributes"]["0"])
    @tv_episode_info = @tv_season_info.tv_episodes.new(tv_show_params["tv_episodes_attributes"]["0"])
    @tv_owner_info = @tv_episode_info.tv_owners.new["tv_owners_attributes"]["0"]
    @tv_show.tv_owners.first.user_id = current_user.id

    if @tv_show.save
      redirect_to @tv_show, notice: 'Tv show was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tv_shows/1
  def update
    @tv_show = TvShow.find(params[:id])
    if @tv_show.update(tv_show_params)
      redirect_to @tv_show, notice: 'Tv show was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tv_shows/1
  def destroy
    @tv_show = TvShow.find(params[:id])
    @tv_show.destroy
    redirect_to tv_shows_url, notice: 'Tv show was successfully destroyed.'
  end

  def get_tv_shows
    name = params[:name]
    @tv_show = TvShow.find_or_initialize_by(name: params[:name])
    if @tv_show.new_record?
      @tv_show_info = TvShow.find_initial_tv_show_info(name)
      render json: @tv_show_info
    else
      redirect_to @tv_show
    end
  end

  def get_tv_show_info
    more_tv_show_info = TvShow.find_more_tv_show_info(params[:tmdb_show_id])
    @tv_show = TvShow.find_or_initialize_by(tmdb_show_id: params[:tmdb_show_id])
    if @tv_show.new_record?
      @tv_season_info = more_tv_show_info
      render json: @tv_season_info
    else
      # @tv_show.tv_owner.create(user_id: current_user.id, tv_show_id: @tv_show.id, notes: params[:notes])
      redirect_to @tv_show
    end
  end

  def get_tv_season_info
    tmdb_show_id = params[:tmdb_show_id]
    season_number = params[:season_number]
    more_tv_season_info = TvSeason.find_more_tv_season_info(tmdb_show_id, season_number)
    @tv_season = TvSeason.find_or_initialize_by(tmdb_season_id: more_tv_season_info["id"])
    if @tv_season.new_record?
      tv_season_info = Hash.new
      tv_season_info = more_tv_season_info.merge(
                    tmdb_show_id: params[:tmdb_show_id])
      @tv_episode_info = tv_season_info
      render json: @tv_episode_info
    else
      redirect_to @tv_show
    end
  end

  def get_tv_episode_info
    tmdb_show_id = params[:tmdb_show_id]
    season_number = params[:season_number]
    episode_number = params[:episode_number]
    tmdb_episode_id = params[:tmdb_episode_id]
    @tv_episode = TvEpisode.find_or_initialize_by(tmdb_episode_id: params[:tmdb_episode_id])
    if @tv_episode.new_record?
      more_tv_show_info = TvShow.find_more_tv_show_info(params[:tmdb_show_id])
      more_tv_season_info = TvSeason.find_more_tv_season_info(tmdb_show_id, season_number)
      tv_episodes = more_tv_season_info["episodes"]
      more_tv_episode_info = tv_episodes.select { |episode| episode["id"] == tmdb_episode_id.to_i }.reduce
      if more_tv_show_info["poster_path"].nil?
        show_poster_path = more_tv_show_info["poster_path"]
      else
        show_poster_path = "http://image.tmdb.org/t/p/w185/#{more_tv_show_info["poster_path"]}"
      end
      if more_tv_season_info["poster_path"].nil?
        season_poster_path = more_tv_season_info["poster_path"]
      else
        season_poster_path = "http://image.tmdb.org/t/p/w185/#{more_tv_season_info["poster_path"]}"
      end
      if more_tv_episode_info["still_path"].nil?
        episode_image_url = more_tv_episode_info["still_path"]
      else
        episode_image_url = "http://image.tmdb.org/t/p/w185/#{more_tv_episode_info["still_path"]}"
      end
      tv_show_params = Hash.new
      tv_show_params = tv_show_params.merge(
                    name: more_tv_show_info["name"],
                    tmdb_show_id: params[:tmdb_show_id],
                    overview: more_tv_show_info["overview"],
                    first_air_date: more_tv_show_info["first_air_date"],
                    last_air_date: more_tv_show_info["last_air_date"],
                    number_of_seasons: more_tv_show_info["number_of_seasons"],
                    number_of_episodes: more_tv_show_info["number_of_episodes"],
                    show_poster_path: show_poster_path,
                    season_name: more_tv_season_info["name"],
                    tmdb_season_id: more_tv_season_info["id"],
                    season_overview: more_tv_season_info["overview"],
                    season_air_date: more_tv_season_info["air_date"],
                    season_number: more_tv_season_info["season_number"],
                    season_poster_path: season_poster_path,
                    episode_title: more_tv_episode_info["name"],
                    tmdb_episode_id: params[:tmdb_episode_id],
                    episode_description: more_tv_episode_info["overview"],
                    episode_air_date: more_tv_episode_info["air_date"],
                    episode_number: params[:episode_number],
                    season_number: params[:season_number],
                    episode_image_url: episode_image_url)
      redirect_to new_tv_show_path(tv_show_params)
    else
      redirect_to @tv_show
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def tv_show_params
    params.require(:tv_show).permit(:name, :tmdb_show_id, :overview, :first_air_date, :last_air_date, :number_of_seasons, :number_of_episodes, :show_poster_path, :tv_seasons_attributes [:id, :name, :tmdb_season_id, :tv_show_id, :overview, :air_date, :season_number, :season_poster_path, :tv_episodes_attributes [:id, :title, :tmdb_episode_id, :description, :air_date, :episode_number, :season_number, :tvshow_image_url, :tv_owners_attributes [:id, :user_id, :tv_episode_id, :notes, :watched]]])
  end
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/tv_shows/_episodeform.html.erb
  <%# title %>
  <div class="form-group">
    <%= f.label(:title, "TV Episode Title", class: "col-sm-3 control-label") %>
    <div class="col-sm-9">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>


  <%# tmdb_episode_id %>
  <div class="form-group">
    <%= f.label(:tmdb_episode_id, "TMDb Episode ID", class: "col-sm-3 control-label") %>
    <div class="col-sm-9">
      <%= f.number_field :tmdb_episode_id, class: "form-control" %>
    </div>
  </div>


  <%# description %>
  <div class="form-group">
    <%= f.label(:description, "Episode Description", class: "col-sm-3 control-label") %>
    <div class="col-sm-9">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>


  <%# air_date %>
  <div class="form-group">
    <%= f.label(:air_date, "Episode Air Date", class: "col-sm-3 control-label") %>
    <div class="col-sm-9">
      <%= f.text_field :air_date, class: "form-control" %>
    </div>
  </div>


  <%# episode_number %>
  <div class="form-group">
    <%= f.label(:episode_number, "Episode Number", class: "col-sm-3 control-label") %>
    <div class="col-sm-9">
      <%= f.number_field :episode_number, class: "form-control" %>
    </div>
  </div>


  <%# season_number %>
  <div class="form-group">
    <%= f.label(:season_number, "Season Number", class: "col-sm-3 control-label") %>
    <div class="col-sm-9">
      <%= f.number_field :season_number, class: "form-control" %>
    </div>
  </div>


  <%# episode_image_url %>
  <div class="form-group">
    <%= f.label(:episode_image_url, "TV Episode Image Link", class: "col-sm-3 control-label") %>
    <div class="col-sm-9">
      <%= f.text_field :episode_image_url, class: "form-control" %>
    </div>
  </div>


  <%# tv_season_id %>
  <div class="form-group">
    <%= f.label(:tv_season_id, "TV Season ID", class: "col-sm-3 control-label") %>
    <div class="col-sm-9">
      <%= f.text_field :tv_season_id, class: "form-control" %>
    </div>
  </div>


  <%= f.fields_for :tv_owners, @tv_owner_info do |builder| %>
    <%= render 'tvownerform', f: builder %>
  <% end %>

app/views/tv_shows/_seasonform.html.erb
  <%# name %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>


  <%# tmdb_season_id %>
  <div class="form-group">
    <%= f.label :tmdb_season_id, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.number_field :tmdb_season_id, class: "form-control" %>
    </div>
  </div>


  <%# tv_show %>
  <div class="form-group">
    <%= f.label :tv_show, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :tv_show, class: "form-control" %>
    </div>
  </div>


  <%# overview %>
  <div class="form-group">
    <%= f.label :overview, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :overview, class: "form-control" %>
    </div>
  </div>


  <%# air_date %>
  <div class="form-group">
    <%= f.label :air_date, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :air_date, class: "form-control" %>
    </div>
  </div>


  <%# season_number %>
  <div class="form-group">
    <%= f.label :season_number, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.number_field :season_number, class: "form-control" %>
    </div>
  </div>


  <%# season_poster_path %>
  <div class="form-group">
    <%= f.label :season_poster_path, class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :season_poster_path, class: "form-control" %>
    </div>
  </div>

app/views/tv_shows/_tv_show.html.erb
<li class="box">
  <% if tv_show.show_poster_path.nil? || tv_show.show_poster_path.empty? %>
    <%= link_to tv_show do %>
      <%= image_tag("genericperson.png") %>
    <% end %>
  <% else %>
    <%= link_to tv_show do %>
      <%= image_tag tv_show.show_poster_path %>
    <% end %>
  <% end %>
  <div class="textline">
    <div class="firsttextline">
      <p class="s-text"><%= truncate(tv_show.name, length: 44, seperator: ' ') %></p>
    </div>
  </div>
  <div class="textline">
    <div class="heartbox">
      <% if user_signed_in? && tv_favorited(tv_show.id) == true %>
        <p class="tv-faved-heart" data-remote=true data-type=script data-tvshowid="<%= tv_show.id %>"><i class="fa fa-heart" aria-hidden="true"></i></p>
      <% elsif user_signed_in? && tv_favorited(tv_show.id) == false %>
        <p class="tv-fav-heart" data-remote=true data-type=script data-tvshowid="<%= tv_show.id %>"><i class="fa fa-heart" aria-hidden="true"></i></p>
      <% end %>
    </div>
  </div>
</li>

app/views/tv_shows/comingsoon.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>Library
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'coming-soon', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <style>

  </style>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%> coming-soon-body">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "/", class: "navbar-brand" do %>
          My Media Library
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Movies", movies_path(sort: 'title') %></li>
          <li><%= link_to "TV Shows", tv_shows_path %></li>
          <li><%= link_to "Games", games_path(sort: 'title') %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right pull-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">

    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

  </div>
  <div class="container">
    <div class="text-center coming-soon-header">
      <h1 Listing>New Shows</h1>
    </div>
    <div class="coming-soon-flexbox">
      <%= image_tag "source.gif", class: "coming-soon" %>
    </div>
  </div>
</body>
</html>

app/views/tv_shows/edit.html.erb
<div class="container">
  <div class="page-header custom-header">
    <%= link_to tv_shows_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to @tv_show, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-info-sign"></span>
      Show
    <% end %>
    <h1>Editing TV Show</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/tv_shows/index.html.erb
<div class="container">
  <div class="page-header custom-header">
    <div class="header-flexbox">
      <div class="flextitle">
        <h1 Listing>TV Shows </h1>
      </div>
      <div class="social-flexbox">
        <div class="well well-sm custom-well text-center">
          <h5>Share what you are watching with your friends!</h5>
          <div class="text-center">
            <%= social_share_button_tag %>
          </div>
        </div>
      </div>
      <div>
      <%= link_to new_tv_show_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-plus"></span>
        New TV Show
      <% end %>
      <%= link_to new_tv_season_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-plus"></span>
        New TV Season
      <% end %>
      <%= link_to new_tv_episode_path, class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-plus"></span>
        New TV Episode
      <% end %>
    </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="s-ul">
    <%= render @tv_shows %>
  </div>

  <div class="text-center" id='paginator'>
    <%= paginate @tv_shows, remote: true %><br>
    <%= page_entries_info @tv_shows %>
    <p>Logged in as <%= current_user.email %></p>
  </div>
  <div class="col-md-2 col-md-offset-10 text-center api-logo">
      <a href="https://www.themoviedb.org/?language=en" height="50px"><%= image_tag("408x161-powered-by-rectangle-green sm.png") %></a>
  </div>
</div>

<div class="container">
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>tmdb show id</th>
        <th>Overview</th>
        <th>First air date</th>
        <th>Last air date</th>
        <th>Number of seasons</th>
        <th>Number of episodes</th>
        <th>Show poster path</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="table-body">
      <%- @tv_shows.each do |tv_show| %>
      <tr>
        <td><%= tv_show.name %></td>
        <td><%= tv_show.tmdb_show_id %></td>
        <td><%= tv_show.overview %></td>
        <td><%= tv_show.first_air_date %></td>
        <td><%= tv_show.last_air_date %></td>
        <td><%= tv_show.number_of_seasons %></td>
        <td><%= tv_show.number_of_episodes %></td>
        <td><%= tv_show.show_poster_path %></td>
        <td>
          <%= link_to tv_show do %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_tv_show_path(tv_show) do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to tv_show, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/tv_shows/new.html.erb
<div class="container">
  <div class="page-header custom-header">
    <%= link_to tv_shows_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <h1>New TV Show</h1>
  </div>
  <div class="tv-search-flexbox">
    <div class="form-inline">
      <div class="form-group">
        <%= text_field_tag :tv_show_name, params[:tv_show_name], id: 'tv-show-name', class: "form-control", placeholder: "Please type the Title of the TV Show Here", style: 'width: 400px' %>
      </div>
      <div class="btn btn-default" id='search-name'>
        <span class="glyphicon glyphicon-search"></span> Search
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <%= render 'form' %>
  </div>
  <div class="spinner">
    <div class="sk-circle1 sk-circle"></div>
    <div class="sk-circle2 sk-circle"></div>
    <div class="sk-circle3 sk-circle"></div>
    <div class="sk-circle4 sk-circle"></div>
    <div class="sk-circle5 sk-circle"></div>
    <div class="sk-circle6 sk-circle"></div>
    <div class="sk-circle7 sk-circle"></div>
    <div class="sk-circle8 sk-circle"></div>
    <div class="sk-circle9 sk-circle"></div>
    <div class="sk-circle10 sk-circle"></div>
    <div class="sk-circle11 sk-circle"></div>
    <div class="sk-circle12 sk-circle"></div>
  </div>
</div>


<div class="modal fade" id="choose-tv-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Click on the Correct Item</h4>
      </div>
      <div class="modal-body">
        <ul class="custom-choice" id='tv-shows-info'>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="choose-season-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Click on the Correct Item</h4>
      </div>
      <div class="modal-body">
        <ul class="custom-choice" id='tv-seasons-info'>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="choose-episode-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Click on the Correct Item</h4>
      </div>
      <div class="modal-body">
        <ul class="custom-choice" id='tv-episodes-info'>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="refresh-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body text-center" id='went-wrong-notice'>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="refresh-ok" data-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/tv_shows/show.html.erb
<div class="container">
  <div class="page-header custom-header">
    <%= link_to tv_shows_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to edit_tv_show_path(@tv_show), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
    <h1>Show tv_show</h1>
  </div>

  <dl class="dl-horizontal">
    <dt>Name:</dt>
    <dd><%= @tv_show.name %></dd>

    <dt>Tmdb show:</dt>
    <dd><%= @tv_show.tmdb_show_id %></dd>

    <dt>Overview:</dt>
    <dd><%= @tv_show.overview %></dd>

    <dt>First air date:</dt>
    <dd><%= @tv_show.first_air_date %></dd>

    <dt>Last air date:</dt>
    <dd><%= @tv_show.last_air_date %></dd>

    <dt>Number of seasons:</dt>
    <dd><%= @tv_show.number_of_seasons %></dd>

    <dt>Number of episodes:</dt>
    <dd><%= @tv_show.number_of_episodes %></dd>

    <dt>Show poster path:</dt>
    <dd><%= @tv_show.show_poster_path %></dd>

  </dl>
</div>