config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'

  resources :tv_shows do
    collection do
      post :get_tv_shows
      post :get_tv_show_info
      post :get_tv_season_info
      post :get_tv_episode_info
    end
  end

  resources :tv_seasons
  resources :tv_episodes

  resources :games do
    collection do
      post :get_barcode
      post :get_game_info
      post :get_games
    end
  end

  devise_for :users

  devise_scope :user do
    get "auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    get "auth/google/callback"   => "users/omniauth_callbacks#google"
    get "auth/linkedin/callback" => "users/omniauth_callbacks#linkedin"
    get "auth/github/callback"   => "users/omniauth_callbacks#github"
  end

  post '/favorites/:movieId'                =>  'favorites#create'
  delete '/favorites/destroy/:movieId'      =>  'favorites#destroy'

  post '/game_favorites/:gameId'            =>  'game_favorites#create'
  delete '/game_favorites/destroy/:gameId'  =>  'game_favorites#destroy'

  post '/tv_favorites/:tvshowId'                =>  'tv_favorites#create'
  delete '/tv_favorites/destroy/:tvshowId'      =>  'tv_favorites#destroy'

  get 'pages/landing'
  get 'pages/comingsoon'
  root 'pages#landing'

  resources :people

  resources :movies do
    collection do
      post :get_barcode
      post :get_movie_info
      post :get_movies
    end
  end

  mount Resque::Server.new, at: "/resque"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tv_episode.rb
class TvEpisode < ApplicationRecord
  belongs_to :tv_season

  has_many :tv_guest_stars, dependent: :destroy
  has_many :people, through: :tv_guest_stars

  has_many :tv_owners, dependent: :destroy, inverse_of: :tv_episode
  accepts_nested_attributes_for :tv_owners
  has_many :users, through: :tv_owners

  validates :tv_season, presence: true
end

app/controllers/tv_episodes_controller.rb
class TvEpisodesController < ApplicationController
  before_action :authenticate_user!
  # GET /tv_episodes
  def index
    @tv_episodes = TvEpisode.all.page(params[:page]).per(24).order('title')
  end

  # GET /tv_episodes/1
  def show
    @tv_episode = TvEpisode.find(params[:id])
  end

  # GET /tv_episodes/new
  def new
    @tv_episode = TvEpisode.new
  end

  # GET /tv_episodes/1/edit
  def edit
    @tv_episode = TvEpisode.find(params[:id])
  end

  # POST /tv_episodes
  def create
    @tv_episode = TvEpisode.new(tv_episode_params)

    if @tv_episode.save
      redirect_to @tv_episode, notice: 'Tv episode was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tv_episodes/1
  def update
    @tv_episode = TvEpisode.find(params[:id])
    if @tv_episode.update(tv_episode_params)
      redirect_to @tv_episode, notice: 'Tv episode was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tv_episodes/1
  def destroy
    @tv_episode = TvEpisode.find(params[:id])
    @tv_episode.destroy
    redirect_to tv_episodes_url, notice: 'Tv episode was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def tv_episode_params
    params.require(:tv_episode).permit(:title, :tmdb_episode_id, :description, :air_date, :episode_number, :season_number, :tvshow_image_url)
  end
end

app/helpers/tv_episodes_helper.rb
module TvEpisodesHelper
end

app/views/tv_episodes/_form.html.erb
<%= form_for(@tv_episode, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @tv_episode.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@tv_episode.errors.count, "error") %> prohibited this tv_episode from being saved:</h4>

      <ul>
      <% @tv_episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# title %>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>


  <%# tmdb_episode_id %>
  <div class="form-group">
    <%= f.label :tmdb_episode_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :tmdb_episode_id, class: "form-control" %>
    </div>
  </div>


  <%# description %>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>


  <%# air_date %>
  <div class="form-group">
    <%= f.label :air_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :air_date, class: "form-control" %>
    </div>
  </div>


  <%# episode_number %>
  <div class="form-group">
    <%= f.label :episode_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :episode_number, class: "form-control" %>
    </div>
  </div>


  <%# season_number %>
  <div class="form-group">
    <%= f.label :season_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :season_number, class: "form-control" %>
    </div>
  </div>


  <%= f.fields_for :tv_owners, @tv_owner_info do |builder| %>
    <%= render 'tvownerform', f: builder %>
  <% end %>


  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>
<% end -%>

app/views/tv_episodes/edit.html.erb
<div class="container">
  <div class="page-header custom-header">
    <%= link_to tv_episodes_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to @tv_episode, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-info-sign"></span>
      Show
    <% end %>
    <h1>Editing TV Episode</h1>
  </div>
</div>

<div class="container">
  <%= render 'form' %>
</div>

app/views/tv_episodes/index.html.erb
<div class="container">
  <div class="page-header custom-header">
    <div class="header-flexbox">
      <div class="flextitle">
        <h1 Listing>TV Episodes </h1>
      </div>
      <div class="social-flexbox">
        <div class="well well-sm custom-well text-center">
          <h5>Share what you are watching with your friends!</h5>
          <div class="text-center">
            <%= social_share_button_tag %>
          </div>
        </div>
      </div>
      <div>
        <%= link_to new_tv_episode_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-plus"></span>
          New TV Episode
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="s-ul">
    <%= render @tv_episodes %>
  </div>
  <div class="text-center" id='paginator'>
    <%= paginate @tv_episodes, remote: true %><br>
    <%= page_entries_info @tv_episodes %>
    <p>Logged in as <%= current_user.email %></p>
  </div>
  <div class="col-md-2 col-md-offset-10 text-center api-logo">
      <a href="https://www.themoviedb.org/?language=en" height="50px"><%= image_tag("408x161-powered-by-rectangle-green sm.png") %></a>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Tmdb episode</th>
        <th>Description</th>
        <th>Air date</th>
        <th>Episode number</th>
        <th>Season number</th>
        <th>Tvshow image url</th>
        <th>TV Season</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="table-body">
      <%- @tv_episodes.each do |tv_episode| %>
      <tr>
        <td><%= tv_episode.title %></td>
        <td><%= tv_episode.tmdb_episode_id %></td>
        <td><%= tv_episode.description %></td>
        <td><%= tv_episode.air_date %></td>
        <td><%= tv_episode.episode_number %></td>
        <td><%= tv_episode.season_number %></td>
        <td><%= tv_episode.tvshow_image_url %></td>
        <td><%= tv_episode.tv_season %></td>
        <td>
          <%= link_to tv_episode do %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_tv_episode_path(tv_episode) do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to tv_episode, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tv_episodes/index1.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>Library
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'coming-soon', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <style>

  </style>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%> coming-soon-body">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "/", class: "navbar-brand" do %>
          My Media Library
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Movies", movies_path(sort: 'title') %></li>
          <li><%= link_to "TV Shows", tv_episodes_path %></li>
          <li><%= link_to "Games", games_path(sort: 'title') %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right pull-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">

    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

  </div>
  <div class="container">
    <div class="text-center coming-soon-header">
      <h1 Listing>New Shows</h1>
    </div>
    <div class="coming-soon-flexbox">
      <%= image_tag "source.gif", class: "coming-soon" %>
    </div>
  </div>
</body>
</html>

app/views/tv_episodes/new.html.erb
<div class="container">
  <div class="page-header custom-header">
    <%= link_to tv_episodes_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <h1>New TV Episode</h1>
  </div>

  <%= render 'form' %>
</div>

app/views/tv_episodes/show.html.erb
<div class="container">
  <div class="page-header custom-header">
    <div class="header-flexbox">
      <div class="flextitle">
        <h1 Listing>TV Episode Details </h1>
      </div>
      <div class="social-flexbox">
        <div class="well well-sm custom-well text-center">
          <h5>Share what you are watching with your friends!</h5>
          <div class="text-center">
            <%= social_share_button_tag(@tv_show.title, :url => "http://my-media-library.com", allow_sites: %w(twitter facebook linkedin)) %>
          </div>
        </div>
      </div>
      <div>
        <%= link_to @tv_episode, class:'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        Delete
        <% end %>
        <%= link_to tv_episodes_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
        <% end %>
        <%= link_to edit_tv_episode_path(@tv_episode), class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
        <% end %>
      </div>
    </div>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @tv_episode.title %></dd>

  <dt>Tmdb episode:</dt>
  <dd><%= @tv_episode.tmdb_episode_id %></dd>

  <dt>Description:</dt>
  <dd><%= @tv_episode.description %></dd>

  <dt>Air date:</dt>
  <dd><%= @tv_episode.air_date %></dd>

  <dt>Episode number:</dt>
  <dd><%= @tv_episode.episode_number %></dd>

  <dt>Season number:</dt>
  <dd><%= @tv_episode.season_number %></dd>

  <dt>Tvshow image url:</dt>
  <dd><%= @tv_episode.tvshow_image_url %></dd>

  <dt>Created by:</dt>
  <dd><%= @tv_episode.created_by_id %></dd>

</dl>